---
---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: go-app
  labels:
    app: go-app
spec:
  type: LoadBalancer  # Changed to LoadBalancer to get a public IP
  ports:
  - name: http
    port: 8001
    targetPort: 8001  # Optional: specifies the container port to forward to
    protocol: TCP
  selector:
    app: go-app
